### ISSUE TITLE
The application picks the wrong IP address

### ISSUE THREAD

**Issue by rgelb** [thura10/airwave#1]
When I click Receive File, it shows the wrong IP address.  Specifically, 169.254.0.97 - which is the auto-configuration IPv4 address.  It should show 192.168.0.12 - which is my wifi address (that's how I connect).

Here is the output of `ipconfig` command:

Windows IP Configuration

Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : corp.mywork.com

Ethernet adapter vEthernet (Default Switch):

   Connection-specific DNS Suffix  . :
   Autoconfiguration IPv4 Address. . : 169.254.0.97
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :

Ethernet adapter vEthernet (nat):

   Connection-specific DNS Suffix  . :
   Autoconfiguration IPv4 Address. . : 169.254.177.164
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :

Wireless LAN adapter Local Area Connection* 3:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Local Area Connection* 12:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter VMware Network Adapter VMnet1:

   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 192.168.144.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VMware Network Adapter VMnet8:

   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 192.168.190.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter Ethernet 3:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . : socal.rr.com
   IPv4 Address. . . . . . . . . . . : 192.168.0.12
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.1

**Comment by thura10** [comment]
Right now, the issue seems occur if you have more than one ethernet/WiFi adapter. In your case, it seems to be the switch ones.
`var os= require('os');
var interfaces = os.networkInterfaces();
var addresses = [];
for (var k in interfaces) {
    for (var k2 in interfaces[k]) {
        var address = interfaces[k][k2];
        if (address.family === 'IPv4' && !address.internal) {
            addresses.push(address.address);
        }
    }
}`

Right now, I get the IP address using the above method. I'm unsure of a better way to do this. But if you know a better way, I'd be happy to change it. I will try using a different method in the weekend when I have more time.

**Comment by rgelb** [comment]
My first thought was to ignore entries that do not have Default Gateway defined.  But it appears that `os.networkInterfaces()` doesn't return that information.   You could rely on the [network](https://www.npmjs.com/package/network) package and utilize `network.get_active_interface` method.  

Looking at how the `network` package implements the functionality, it appears that it has a platform specific file (win32.js, linux.js, darwin.js) to deal with each OS.  You could just copy the win32.js implementation since your application only cares about windows.
