### ISSUE TITLE
what about for linux?

### ISSUE THREAD

**Issue by zeus-dev** [thura10/airwave#13]
airwave support linux machines?

**Comment by MinerChAI** [comment]
There’s some windows only code, like creating hotspot

**Comment by zeus-dev** [comment]
ok thanks

**Comment by thura10** [comment]
I didn't consider this to be run on other platforms so the code is extremely non-cross-platform. If I have more time, I'll try to make it more streamlined but I don't have a linux machine to test on, so this would be very hard.
