### ISSUE TITLE
Sending files does not work

### ISSUE THREAD

**Issue by FeBe95** [thura10/airwave#16]
Hey there, unfortunately the app's functionality is broken atm.

Why? Because iOS Shortcuts converts every URL from http to https now?!

In order to work again, the local airwave server needs to have https implemented. It seems to work just fine with a self signed certificate (I can access my local Raspberry Pi server that uses a self signed ssl cert)!

I created a test shortcut to demonstrate this unexpected behavior ("Übersicht" = "Quick Look"):

![shortcut](https://user-images.githubusercontent.com/7470739/99088353-39e81800-25cc-11eb-8089-0274c6a30ede.png)

**Comment by thura10** [comment]
Thanks for the in-depth explanation. Seems easy enough to fix. Will try to fix in a week or two.

**Comment by FeBe95** [comment]
Hey again, do you have an updated ETA on this? :)

**Comment by thura10** [comment]
Hey, this totally went to the back of my mind. I can attempt this at the end of the month, I might be free by then. Thanks for the reminder!

**Comment by FeBe95** [comment]
Soo... I tried my luck and started fixing it.

## Self-Signed Certificate
After some exploration I found out that the shortcuts app doesn't like self-signed certificates (I made a wrong assumption back then). Even after installing the self-signed certificate as a root certificate on the iPhone itself it still won't work and displays this error:
![grafik](https://user-images.githubusercontent.com/7470739/110980128-cda4d780-8365-11eb-8fa1-60480cf7454c.png)
It works just fine when I enter the URL in Safari though... This might be a bug within the shortcuts app then.

## Let's Encrypt
I tried letsencrypt as well, but no luck. Firstly it doesn't seem to support raw ip addresses instead of "real" domains. Secondly it apparently needs to use the standard HTTPS port `443` in combination with the standard HTTP port `80` to work properly. So that won't work either.

## But then...
After I almost gave up trying I noticed that even though the URL-action of the shortcuts app still converts every http URL to https, sending/uploading files works now as it did pre iOS14. I did not change a thing, neither within the shortcut or airwave. It just works again.. MAGIC

I am sorry if I wasted your time but it seems to work flawlessly again at the moment. Using https would be better in the long run but as long as it works again I won't complain ;)

Feel free to close this issue if you don't plan to implement SSL support for now or keep it open otherwise. Cheers
