### ISSUE TITLE
cross-plattform support

### ISSUE THREAD

**Issue by tristan-k** [thura10/airwave#2]
Are there any plans to runs this on Linux and macOS as well?

**Comment by thura10** [comment]
Would have to change a few parts. Especially the hotspot creation. I'm willing to help but no longer have as much time anymore. I feel it is useless on Mac and I don't have Linux. If you can try running it on Linux, I think the basic should work as most of it are NPM or electron modules.

**Comment by MinerChAI** [comment]
I can help with Linux
