### ISSUE TITLE
Program overlaps with windows taskbar.

### ISSUE THREAD

**Issue by ELAPSEM** [thura10/airwave#4]
I use windows taskbar to right corner not a bottom.
When I use airwave, program overlaps with windows taskbar that you can check on screenshot.

So I can access a close button cause that located behind taskbar.

Please check that  issues.

Thanks

![image](https://user-images.githubusercontent.com/40282148/74500835-8adabb00-4f2b-11ea-9f13-fb6b9a666f6f.png)

**Comment by thura10** [comment]
I hadn't considered this. Will try to add in a new release. Thanks.

**Comment by thura10** [comment]
Fixed in latest commit
https://github.com/thura10/airwave/commit/9cc103bd1cb061543546e7eaf61b95f50ea209d1
