### ISSUE TITLE
Port issue

### ISSUE THREAD

**Issue by FeBe95** [thura10/airwave#7]
I had a node server running at port 3000. When trying to use airwave a JavaScript error window popped up and stated that this port is already in use. Maybe a setting to change the port for the airport server could be useful.

**Comment by thura10** [comment]
Easily addable. Will do in a new release.

**Comment by FeBe95** [comment]
Perfect. I think the default 3000 works fine for most people. Just add a try & catch around the server start method and show the settings page if the start didn't work.

**Comment by thura10** [comment]
Just a reminder, I will add a way to change the port in settings but you will have to go into the shortcut and change the port manually as well. And 'get contents of url' is done multiple times in each shortcuts so you might have to change multiple times.

**Comment by thura10** [comment]
done with this commit.
https://github.com/thura10/airwave/commit/723667227f7d8635e3ac95957273cd3907bbf9f8
